// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/repositories/video_controller_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;
import 'dart:convert' as _i15;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i10;

import 'package:file/file.dart' as _i5;
import 'package:flutter/material.dart' as _i12;
import 'package:flutter_cache_manager/flutter_cache_manager.dart' as _i2;
import 'package:flutter_cache_manager/src/cache_store.dart' as _i3;
import 'package:flutter_cache_manager/src/web/web_helper.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i14;
import 'package:openvine/services/age_verification_service.dart' as _i11;
import 'package:openvine/services/blossom_auth_service.dart' as _i13;
import 'package:openvine/services/broken_video_tracker.dart' as _i9;
import 'package:openvine/services/video_cache_manager.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConfig_0 extends _i1.SmartFake implements _i2.Config {
  _FakeConfig_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCacheStore_1 extends _i1.SmartFake implements _i3.CacheStore {
  _FakeCacheStore_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWebHelper_2 extends _i1.SmartFake implements _i4.WebHelper {
  _FakeWebHelper_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_3 extends _i1.SmartFake implements _i5.File {
  _FakeFile_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileInfo_4 extends _i1.SmartFake implements _i2.FileInfo {
  _FakeFileInfo_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFile_5 extends _i1.SmartFake implements _i6.File {
  _FakeFile_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUri_6 extends _i1.SmartFake implements Uri {
  _FakeUri_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDirectory_7 extends _i1.SmartFake implements _i6.Directory {
  _FakeDirectory_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileSystemEntity_8 extends _i1.SmartFake
    implements _i6.FileSystemEntity {
  _FakeFileSystemEntity_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDateTime_9 extends _i1.SmartFake implements DateTime {
  _FakeDateTime_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRandomAccessFile_10 extends _i1.SmartFake
    implements _i6.RandomAccessFile {
  _FakeRandomAccessFile_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIOSink_11 extends _i1.SmartFake implements _i6.IOSink {
  _FakeIOSink_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeFileStat_12 extends _i1.SmartFake implements _i6.FileStat {
  _FakeFileStat_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VideoCacheManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoCacheManager extends _i1.Mock implements _i7.VideoCacheManager {
  @override
  _i2.Config get config =>
      (super.noSuchMethod(
            Invocation.getter(#config),
            returnValue: _FakeConfig_0(this, Invocation.getter(#config)),
            returnValueForMissingStub: _FakeConfig_0(
              this,
              Invocation.getter(#config),
            ),
          )
          as _i2.Config);

  @override
  _i3.CacheStore get store =>
      (super.noSuchMethod(
            Invocation.getter(#store),
            returnValue: _FakeCacheStore_1(this, Invocation.getter(#store)),
            returnValueForMissingStub: _FakeCacheStore_1(
              this,
              Invocation.getter(#store),
            ),
          )
          as _i3.CacheStore);

  @override
  _i4.WebHelper get webHelper =>
      (super.noSuchMethod(
            Invocation.getter(#webHelper),
            returnValue: _FakeWebHelper_2(this, Invocation.getter(#webHelper)),
            returnValueForMissingStub: _FakeWebHelper_2(
              this,
              Invocation.getter(#webHelper),
            ),
          )
          as _i4.WebHelper);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<_i6.File?> cacheVideo(
    String? videoUrl,
    String? videoId, {
    _i9.BrokenVideoTracker? brokenVideoTracker,
    Map<String, String>? authHeaders,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #cacheVideo,
              [videoUrl, videoId],
              {
                #brokenVideoTracker: brokenVideoTracker,
                #authHeaders: authHeaders,
              },
            ),
            returnValue: _i8.Future<_i6.File?>.value(),
            returnValueForMissingStub: _i8.Future<_i6.File?>.value(),
          )
          as _i8.Future<_i6.File?>);

  @override
  _i8.Future<bool> isVideoCached(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#isVideoCached, [videoId]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<_i6.File?> getCachedVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVideo, [videoId]),
            returnValue: _i8.Future<_i6.File?>.value(),
            returnValueForMissingStub: _i8.Future<_i6.File?>.value(),
          )
          as _i8.Future<_i6.File?>);

  @override
  _i6.File? getCachedVideoSync(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#getCachedVideoSync, [videoId]),
            returnValueForMissingStub: null,
          )
          as _i6.File?);

  @override
  _i8.Future<void> preCache(List<String>? videoUrls, List<String>? videoIds) =>
      (super.noSuchMethod(
            Invocation.method(#preCache, [videoUrls, videoIds]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<Map<String, dynamic>> getCacheStats() =>
      (super.noSuchMethod(
            Invocation.method(#getCacheStats, []),
            returnValue: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
            returnValueForMissingStub: _i8.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i8.Future<Map<String, dynamic>>);

  @override
  _i8.Future<void> removeCorruptedVideo(String? videoId) =>
      (super.noSuchMethod(
            Invocation.method(#removeCorruptedVideo, [videoId]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> clearAllCache() =>
      (super.noSuchMethod(
            Invocation.method(#clearAllCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void resetForTesting() => super.noSuchMethod(
    Invocation.method(#resetForTesting, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i5.File> getSingleFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getSingleFile,
              [url],
              {#key: key, #headers: headers},
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #getSingleFile,
                  [url],
                  {#key: key, #headers: headers},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #getSingleFile,
                  [url],
                  {#key: key, #headers: headers},
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i8.Stream<_i2.FileInfo> getFile(
    String? url, {
    String? key,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getFile, [url], {#key: key, #headers: headers}),
            returnValue: _i8.Stream<_i2.FileInfo>.empty(),
            returnValueForMissingStub: _i8.Stream<_i2.FileInfo>.empty(),
          )
          as _i8.Stream<_i2.FileInfo>);

  @override
  _i8.Stream<_i2.FileResponse> getFileStream(
    String? url, {
    String? key,
    Map<String, String>? headers,
    bool? withProgress = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileStream,
              [url],
              {#key: key, #headers: headers, #withProgress: withProgress},
            ),
            returnValue: _i8.Stream<_i2.FileResponse>.empty(),
            returnValueForMissingStub: _i8.Stream<_i2.FileResponse>.empty(),
          )
          as _i8.Stream<_i2.FileResponse>);

  @override
  _i8.Future<_i2.FileInfo> downloadFile(
    String? url, {
    String? key,
    Map<String, String>? authHeaders,
    bool? force = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadFile,
              [url],
              {#key: key, #authHeaders: authHeaders, #force: force},
            ),
            returnValue: _i8.Future<_i2.FileInfo>.value(
              _FakeFileInfo_4(
                this,
                Invocation.method(
                  #downloadFile,
                  [url],
                  {#key: key, #authHeaders: authHeaders, #force: force},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i2.FileInfo>.value(
              _FakeFileInfo_4(
                this,
                Invocation.method(
                  #downloadFile,
                  [url],
                  {#key: key, #authHeaders: authHeaders, #force: force},
                ),
              ),
            ),
          )
          as _i8.Future<_i2.FileInfo>);

  @override
  _i8.Future<_i2.FileInfo?> getFileFromCache(
    String? key, {
    bool? ignoreMemCache = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getFileFromCache,
              [key],
              {#ignoreMemCache: ignoreMemCache},
            ),
            returnValue: _i8.Future<_i2.FileInfo?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.FileInfo?>.value(),
          )
          as _i8.Future<_i2.FileInfo?>);

  @override
  _i8.Future<_i2.FileInfo?> getFileFromMemory(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#getFileFromMemory, [key]),
            returnValue: _i8.Future<_i2.FileInfo?>.value(),
            returnValueForMissingStub: _i8.Future<_i2.FileInfo?>.value(),
          )
          as _i8.Future<_i2.FileInfo?>);

  @override
  _i8.Future<_i5.File> putFile(
    String? url,
    _i10.Uint8List? fileBytes, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFile,
              [url, fileBytes],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #putFile,
                  [url, fileBytes],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #putFile,
                  [url, fileBytes],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i8.Future<_i5.File> putFileStream(
    String? url,
    _i8.Stream<List<int>>? source, {
    String? key,
    String? eTag,
    Duration? maxAge = const Duration(days: 30),
    String? fileExtension = 'file',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putFileStream,
              [url, source],
              {
                #key: key,
                #eTag: eTag,
                #maxAge: maxAge,
                #fileExtension: fileExtension,
              },
            ),
            returnValue: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #putFileStream,
                  [url, source],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i5.File>.value(
              _FakeFile_3(
                this,
                Invocation.method(
                  #putFileStream,
                  [url, source],
                  {
                    #key: key,
                    #eTag: eTag,
                    #maxAge: maxAge,
                    #fileExtension: fileExtension,
                  },
                ),
              ),
            ),
          )
          as _i8.Future<_i5.File>);

  @override
  _i8.Future<void> removeFile(String? key) =>
      (super.noSuchMethod(
            Invocation.method(#removeFile, [key]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> emptyCache() =>
      (super.noSuchMethod(
            Invocation.method(#emptyCache, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [AgeVerificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAgeVerificationService extends _i1.Mock
    implements _i11.AgeVerificationService {
  @override
  bool get isAgeVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isAgeVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get isAdultContentVerified =>
      (super.noSuchMethod(
            Invocation.getter(#isAdultContentVerified),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i11.AdultContentPreference get adultContentPreference =>
      (super.noSuchMethod(
            Invocation.getter(#adultContentPreference),
            returnValue: _i11.AdultContentPreference.alwaysShow,
            returnValueForMissingStub: _i11.AdultContentPreference.alwaysShow,
          )
          as _i11.AdultContentPreference);

  @override
  bool get shouldAutoShowAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldAutoShowAdultContent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get shouldHideAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldHideAdultContent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  bool get shouldAskForAdultContent =>
      (super.noSuchMethod(
            Invocation.getter(#shouldAskForAdultContent),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> setAgeVerified(bool? verified) =>
      (super.noSuchMethod(
            Invocation.method(#setAgeVerified, [verified]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> checkAgeVerification() =>
      (super.noSuchMethod(
            Invocation.method(#checkAgeVerification, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setAdultContentVerified(bool? verified) =>
      (super.noSuchMethod(
            Invocation.method(#setAdultContentVerified, [verified]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> checkAdultContentVerification() =>
      (super.noSuchMethod(
            Invocation.method(#checkAdultContentVerification, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> setAdultContentPreference(
    _i11.AdultContentPreference? preference,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#setAdultContentPreference, [preference]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<bool> verifyAdultContentAccess(_i12.BuildContext? context) =>
      (super.noSuchMethod(
            Invocation.method(#verifyAdultContentAccess, [context]),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  _i8.Future<void> clearVerificationStatus() =>
      (super.noSuchMethod(
            Invocation.method(#clearVerificationStatus, []),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);
}

/// A class which mocks [BlossomAuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBlossomAuthService extends _i1.Mock
    implements _i13.BlossomAuthService {
  @override
  Map<String, dynamic> get cacheStats =>
      (super.noSuchMethod(
            Invocation.getter(#cacheStats),
            returnValue: <String, dynamic>{},
            returnValueForMissingStub: <String, dynamic>{},
          )
          as Map<String, dynamic>);

  @override
  bool get canCreateHeaders =>
      (super.noSuchMethod(
            Invocation.getter(#canCreateHeaders),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<String?> createGetAuthHeader({
    required String? sha256Hash,
    String? serverUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGetAuthHeader, [], {
              #sha256Hash: sha256Hash,
              #serverUrl: serverUrl,
            }),
            returnValue: _i8.Future<String?>.value(),
            returnValueForMissingStub: _i8.Future<String?>.value(),
          )
          as _i8.Future<String?>);

  @override
  void clearCache() => super.noSuchMethod(
    Invocation.method(#clearCache, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [File].
///
/// See the documentation for Mockito's code generation for more information.
class MockFile extends _i1.Mock implements _i6.File {
  @override
  _i6.File get absolute =>
      (super.noSuchMethod(
            Invocation.getter(#absolute),
            returnValue: _FakeFile_5(this, Invocation.getter(#absolute)),
            returnValueForMissingStub: _FakeFile_5(
              this,
              Invocation.getter(#absolute),
            ),
          )
          as _i6.File);

  @override
  String get path =>
      (super.noSuchMethod(
            Invocation.getter(#path),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.getter(#path),
            ),
          )
          as String);

  @override
  Uri get uri =>
      (super.noSuchMethod(
            Invocation.getter(#uri),
            returnValue: _FakeUri_6(this, Invocation.getter(#uri)),
            returnValueForMissingStub: _FakeUri_6(
              this,
              Invocation.getter(#uri),
            ),
          )
          as Uri);

  @override
  bool get isAbsolute =>
      (super.noSuchMethod(
            Invocation.getter(#isAbsolute),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i6.Directory get parent =>
      (super.noSuchMethod(
            Invocation.getter(#parent),
            returnValue: _FakeDirectory_7(this, Invocation.getter(#parent)),
            returnValueForMissingStub: _FakeDirectory_7(
              this,
              Invocation.getter(#parent),
            ),
          )
          as _i6.Directory);

  @override
  _i8.Future<_i6.File> create({
    bool? recursive = false,
    bool? exclusive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#create, [], {
              #recursive: recursive,
              #exclusive: exclusive,
            }),
            returnValue: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(#create, [], {
                  #recursive: recursive,
                  #exclusive: exclusive,
                }),
              ),
            ),
          )
          as _i8.Future<_i6.File>);

  @override
  void createSync({bool? recursive = false, bool? exclusive = false}) =>
      super.noSuchMethod(
        Invocation.method(#createSync, [], {
          #recursive: recursive,
          #exclusive: exclusive,
        }),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i6.File> rename(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#rename, [newPath]),
            returnValue: _i8.Future<_i6.File>.value(
              _FakeFile_5(this, Invocation.method(#rename, [newPath])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.File>.value(
              _FakeFile_5(this, Invocation.method(#rename, [newPath])),
            ),
          )
          as _i8.Future<_i6.File>);

  @override
  _i6.File renameSync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameSync, [newPath]),
            returnValue: _FakeFile_5(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_5(
              this,
              Invocation.method(#renameSync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i8.Future<_i6.FileSystemEntity> delete({bool? recursive = false}) =>
      (super.noSuchMethod(
            Invocation.method(#delete, [], {#recursive: recursive}),
            returnValue: _i8.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_8(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.FileSystemEntity>.value(
              _FakeFileSystemEntity_8(
                this,
                Invocation.method(#delete, [], {#recursive: recursive}),
              ),
            ),
          )
          as _i8.Future<_i6.FileSystemEntity>);

  @override
  void deleteSync({bool? recursive = false}) => super.noSuchMethod(
    Invocation.method(#deleteSync, [], {#recursive: recursive}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i6.File> copy(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copy, [newPath]),
            returnValue: _i8.Future<_i6.File>.value(
              _FakeFile_5(this, Invocation.method(#copy, [newPath])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.File>.value(
              _FakeFile_5(this, Invocation.method(#copy, [newPath])),
            ),
          )
          as _i8.Future<_i6.File>);

  @override
  _i6.File copySync(String? newPath) =>
      (super.noSuchMethod(
            Invocation.method(#copySync, [newPath]),
            returnValue: _FakeFile_5(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
            returnValueForMissingStub: _FakeFile_5(
              this,
              Invocation.method(#copySync, [newPath]),
            ),
          )
          as _i6.File);

  @override
  _i8.Future<int> length() =>
      (super.noSuchMethod(
            Invocation.method(#length, []),
            returnValue: _i8.Future<int>.value(0),
            returnValueForMissingStub: _i8.Future<int>.value(0),
          )
          as _i8.Future<int>);

  @override
  int lengthSync() =>
      (super.noSuchMethod(
            Invocation.method(#lengthSync, []),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i8.Future<DateTime> lastAccessed() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessed, []),
            returnValue: _i8.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastAccessed, [])),
            ),
            returnValueForMissingStub: _i8.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastAccessed, [])),
            ),
          )
          as _i8.Future<DateTime>);

  @override
  DateTime lastAccessedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastAccessedSync, []),
            returnValue: _FakeDateTime_9(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_9(
              this,
              Invocation.method(#lastAccessedSync, []),
            ),
          )
          as DateTime);

  @override
  _i8.Future<dynamic> setLastAccessed(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastAccessed, [time]),
            returnValue: _i8.Future<dynamic>.value(),
            returnValueForMissingStub: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  void setLastAccessedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastAccessedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<DateTime> lastModified() =>
      (super.noSuchMethod(
            Invocation.method(#lastModified, []),
            returnValue: _i8.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastModified, [])),
            ),
            returnValueForMissingStub: _i8.Future<DateTime>.value(
              _FakeDateTime_9(this, Invocation.method(#lastModified, [])),
            ),
          )
          as _i8.Future<DateTime>);

  @override
  DateTime lastModifiedSync() =>
      (super.noSuchMethod(
            Invocation.method(#lastModifiedSync, []),
            returnValue: _FakeDateTime_9(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
            returnValueForMissingStub: _FakeDateTime_9(
              this,
              Invocation.method(#lastModifiedSync, []),
            ),
          )
          as DateTime);

  @override
  _i8.Future<dynamic> setLastModified(DateTime? time) =>
      (super.noSuchMethod(
            Invocation.method(#setLastModified, [time]),
            returnValue: _i8.Future<dynamic>.value(),
            returnValueForMissingStub: _i8.Future<dynamic>.value(),
          )
          as _i8.Future<dynamic>);

  @override
  void setLastModifiedSync(DateTime? time) => super.noSuchMethod(
    Invocation.method(#setLastModifiedSync, [time]),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i6.RandomAccessFile> open({
    _i6.FileMode? mode = _i6.FileMode.read,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#open, [], {#mode: mode}),
            returnValue: _i8.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_10(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.RandomAccessFile>.value(
              _FakeRandomAccessFile_10(
                this,
                Invocation.method(#open, [], {#mode: mode}),
              ),
            ),
          )
          as _i8.Future<_i6.RandomAccessFile>);

  @override
  _i6.RandomAccessFile openSync({_i6.FileMode? mode = _i6.FileMode.read}) =>
      (super.noSuchMethod(
            Invocation.method(#openSync, [], {#mode: mode}),
            returnValue: _FakeRandomAccessFile_10(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
            returnValueForMissingStub: _FakeRandomAccessFile_10(
              this,
              Invocation.method(#openSync, [], {#mode: mode}),
            ),
          )
          as _i6.RandomAccessFile);

  @override
  _i8.Stream<List<int>> openRead([int? start, int? end]) =>
      (super.noSuchMethod(
            Invocation.method(#openRead, [start, end]),
            returnValue: _i8.Stream<List<int>>.empty(),
            returnValueForMissingStub: _i8.Stream<List<int>>.empty(),
          )
          as _i8.Stream<List<int>>);

  @override
  _i6.IOSink openWrite({
    _i6.FileMode? mode = _i6.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#openWrite, [], {
              #mode: mode,
              #encoding: encoding,
            }),
            returnValue: _FakeIOSink_11(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
            returnValueForMissingStub: _FakeIOSink_11(
              this,
              Invocation.method(#openWrite, [], {
                #mode: mode,
                #encoding: encoding,
              }),
            ),
          )
          as _i6.IOSink);

  @override
  _i8.Future<_i10.Uint8List> readAsBytes() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytes, []),
            returnValue: _i8.Future<_i10.Uint8List>.value(_i10.Uint8List(0)),
            returnValueForMissingStub: _i8.Future<_i10.Uint8List>.value(
              _i10.Uint8List(0),
            ),
          )
          as _i8.Future<_i10.Uint8List>);

  @override
  _i10.Uint8List readAsBytesSync() =>
      (super.noSuchMethod(
            Invocation.method(#readAsBytesSync, []),
            returnValue: _i10.Uint8List(0),
            returnValueForMissingStub: _i10.Uint8List(0),
          )
          as _i10.Uint8List);

  @override
  _i8.Future<String> readAsString({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsString, [], {#encoding: encoding}),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#readAsString, [], {#encoding: encoding}),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String readAsStringSync({_i15.Encoding? encoding = const _i15.Utf8Codec()}) =>
      (super.noSuchMethod(
            Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#readAsStringSync, [], {#encoding: encoding}),
            ),
          )
          as String);

  @override
  _i8.Future<List<String>> readAsLines({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLines, [], {#encoding: encoding}),
            returnValue: _i8.Future<List<String>>.value(<String>[]),
            returnValueForMissingStub: _i8.Future<List<String>>.value(
              <String>[],
            ),
          )
          as _i8.Future<List<String>>);

  @override
  List<String> readAsLinesSync({
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
  }) =>
      (super.noSuchMethod(
            Invocation.method(#readAsLinesSync, [], {#encoding: encoding}),
            returnValue: <String>[],
            returnValueForMissingStub: <String>[],
          )
          as List<String>);

  @override
  _i8.Future<_i6.File> writeAsBytes(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsBytes,
              [bytes],
              {#mode: mode, #flush: flush},
            ),
            returnValue: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(
                  #writeAsBytes,
                  [bytes],
                  {#mode: mode, #flush: flush},
                ),
              ),
            ),
          )
          as _i8.Future<_i6.File>);

  @override
  void writeAsBytesSync(
    List<int>? bytes, {
    _i6.FileMode? mode = _i6.FileMode.write,
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(#writeAsBytesSync, [bytes], {#mode: mode, #flush: flush}),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<_i6.File> writeAsString(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
    bool? flush = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #writeAsString,
              [contents],
              {#mode: mode, #encoding: encoding, #flush: flush},
            ),
            returnValue: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
            returnValueForMissingStub: _i8.Future<_i6.File>.value(
              _FakeFile_5(
                this,
                Invocation.method(
                  #writeAsString,
                  [contents],
                  {#mode: mode, #encoding: encoding, #flush: flush},
                ),
              ),
            ),
          )
          as _i8.Future<_i6.File>);

  @override
  void writeAsStringSync(
    String? contents, {
    _i6.FileMode? mode = _i6.FileMode.write,
    _i15.Encoding? encoding = const _i15.Utf8Codec(),
    bool? flush = false,
  }) => super.noSuchMethod(
    Invocation.method(
      #writeAsStringSync,
      [contents],
      {#mode: mode, #encoding: encoding, #flush: flush},
    ),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<bool> exists() =>
      (super.noSuchMethod(
            Invocation.method(#exists, []),
            returnValue: _i8.Future<bool>.value(false),
            returnValueForMissingStub: _i8.Future<bool>.value(false),
          )
          as _i8.Future<bool>);

  @override
  bool existsSync() =>
      (super.noSuchMethod(
            Invocation.method(#existsSync, []),
            returnValue: false,
            returnValueForMissingStub: false,
          )
          as bool);

  @override
  _i8.Future<String> resolveSymbolicLinks() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinks, []),
            returnValue: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
            returnValueForMissingStub: _i8.Future<String>.value(
              _i14.dummyValue<String>(
                this,
                Invocation.method(#resolveSymbolicLinks, []),
              ),
            ),
          )
          as _i8.Future<String>);

  @override
  String resolveSymbolicLinksSync() =>
      (super.noSuchMethod(
            Invocation.method(#resolveSymbolicLinksSync, []),
            returnValue: _i14.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
            returnValueForMissingStub: _i14.dummyValue<String>(
              this,
              Invocation.method(#resolveSymbolicLinksSync, []),
            ),
          )
          as String);

  @override
  _i8.Future<_i6.FileStat> stat() =>
      (super.noSuchMethod(
            Invocation.method(#stat, []),
            returnValue: _i8.Future<_i6.FileStat>.value(
              _FakeFileStat_12(this, Invocation.method(#stat, [])),
            ),
            returnValueForMissingStub: _i8.Future<_i6.FileStat>.value(
              _FakeFileStat_12(this, Invocation.method(#stat, [])),
            ),
          )
          as _i8.Future<_i6.FileStat>);

  @override
  _i6.FileStat statSync() =>
      (super.noSuchMethod(
            Invocation.method(#statSync, []),
            returnValue: _FakeFileStat_12(
              this,
              Invocation.method(#statSync, []),
            ),
            returnValueForMissingStub: _FakeFileStat_12(
              this,
              Invocation.method(#statSync, []),
            ),
          )
          as _i6.FileStat);

  @override
  _i8.Stream<_i6.FileSystemEvent> watch({
    int? events = 15,
    bool? recursive = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#watch, [], {
              #events: events,
              #recursive: recursive,
            }),
            returnValue: _i8.Stream<_i6.FileSystemEvent>.empty(),
            returnValueForMissingStub: _i8.Stream<_i6.FileSystemEvent>.empty(),
          )
          as _i8.Stream<_i6.FileSystemEvent>);
}
