// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/conversation_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:models/models.dart' as _i3;
import 'package:nostr_client/nostr_client.dart' as _i2;
import 'package:openvine/models/dm_models.dart' as _i6;
import 'package:openvine/repositories/dm_repository.dart' as _i4;
import 'package:openvine/services/nip17_inbox_service.dart' as _i7;
import 'package:openvine/services/nip17_message_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNostrClient_0 extends _i1.SmartFake implements _i2.NostrClient {
  _FakeNostrClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNIP17SendResult_1 extends _i1.SmartFake
    implements _i3.NIP17SendResult {
  _FakeNIP17SendResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DMRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDMRepository extends _i1.Mock implements _i4.DMRepository {
  MockDMRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Stream<List<_i6.Conversation>> watchConversations() =>
      (super.noSuchMethod(
            Invocation.method(#watchConversations, []),
            returnValue: _i5.Stream<List<_i6.Conversation>>.empty(),
          )
          as _i5.Stream<List<_i6.Conversation>>);

  @override
  _i5.Stream<List<_i6.DmMessage>> watchMessages(String? peerPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessages, [peerPubkey]),
            returnValue: _i5.Stream<List<_i6.DmMessage>>.empty(),
          )
          as _i5.Stream<List<_i6.DmMessage>>);

  @override
  _i5.Stream<int> watchUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, []),
            returnValue: _i5.Stream<int>.empty(),
          )
          as _i5.Stream<int>);

  @override
  _i5.Future<void> markConversationRead(String? peerPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationRead, [peerPubkey]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveIncomingMessage(_i7.IncomingMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveIncomingMessage, [message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> saveOutgoingMessage({
    required String? rumorId,
    required String? giftWrapId,
    required String? recipientPubkey,
    required String? content,
    required DateTime? createdAt,
    _i7.DmMessageType? type = _i7.DmMessageType.text,
    String? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveOutgoingMessage, [], {
              #rumorId: rumorId,
              #giftWrapId: giftWrapId,
              #recipientPubkey: recipientPubkey,
              #content: content,
              #createdAt: createdAt,
              #type: type,
              #metadata: metadata,
            }),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> startSync() =>
      (super.noSuchMethod(
            Invocation.method(#startSync, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void stopSync() => super.noSuchMethod(
    Invocation.method(#stopSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [NIP17MessageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNIP17MessageService extends _i1.Mock
    implements _i8.NIP17MessageService {
  MockNIP17MessageService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.NostrClient get nostrService =>
      (super.noSuchMethod(
            Invocation.getter(#nostrService),
            returnValue: _FakeNostrClient_0(
              this,
              Invocation.getter(#nostrService),
            ),
          )
          as _i2.NostrClient);

  @override
  _i5.Future<_i3.NIP17SendResult> sendPrivateMessage({
    required String? recipientPubkey,
    required String? content,
    List<List<String>>? additionalTags = const [],
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sendPrivateMessage, [], {
              #recipientPubkey: recipientPubkey,
              #content: content,
              #additionalTags: additionalTags,
            }),
            returnValue: _i5.Future<_i3.NIP17SendResult>.value(
              _FakeNIP17SendResult_1(
                this,
                Invocation.method(#sendPrivateMessage, [], {
                  #recipientPubkey: recipientPubkey,
                  #content: content,
                  #additionalTags: additionalTags,
                }),
              ),
            ),
          )
          as _i5.Future<_i3.NIP17SendResult>);
}
