// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/screens/inbox_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:ui' as _i11;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i9;
import 'package:nostr_sdk/event.dart' as _i10;
import 'package:openvine/models/dm_models.dart' as _i4;
import 'package:openvine/models/user_profile.dart' as _i7;
import 'package:openvine/repositories/dm_repository.dart' as _i2;
import 'package:openvine/services/nip17_inbox_service.dart' as _i5;
import 'package:openvine/services/profile_cache_service.dart' as _i8;
import 'package:openvine/services/user_profile_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [DMRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDMRepository extends _i1.Mock implements _i2.DMRepository {
  MockDMRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.Conversation>> watchConversations() =>
      (super.noSuchMethod(
            Invocation.method(#watchConversations, []),
            returnValue: _i3.Stream<List<_i4.Conversation>>.empty(),
          )
          as _i3.Stream<List<_i4.Conversation>>);

  @override
  _i3.Stream<List<_i4.DmMessage>> watchMessages(String? peerPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#watchMessages, [peerPubkey]),
            returnValue: _i3.Stream<List<_i4.DmMessage>>.empty(),
          )
          as _i3.Stream<List<_i4.DmMessage>>);

  @override
  _i3.Stream<int> watchUnreadCount() =>
      (super.noSuchMethod(
            Invocation.method(#watchUnreadCount, []),
            returnValue: _i3.Stream<int>.empty(),
          )
          as _i3.Stream<int>);

  @override
  _i3.Future<void> markConversationRead(String? peerPubkey) =>
      (super.noSuchMethod(
            Invocation.method(#markConversationRead, [peerPubkey]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveIncomingMessage(_i5.IncomingMessage? message) =>
      (super.noSuchMethod(
            Invocation.method(#saveIncomingMessage, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> saveOutgoingMessage({
    required String? rumorId,
    required String? giftWrapId,
    required String? recipientPubkey,
    required String? content,
    required DateTime? createdAt,
    _i5.DmMessageType? type = _i5.DmMessageType.text,
    String? metadata,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#saveOutgoingMessage, [], {
              #rumorId: rumorId,
              #giftWrapId: giftWrapId,
              #recipientPubkey: recipientPubkey,
              #content: content,
              #createdAt: createdAt,
              #type: type,
              #metadata: metadata,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startSync() =>
      (super.noSuchMethod(
            Invocation.method(#startSync, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void stopSync() => super.noSuchMethod(
    Invocation.method(#stopSync, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [UserProfileService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileService extends _i1.Mock
    implements _i6.UserProfileService {
  MockUserProfileService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Map<String, _i7.UserProfile> get allProfiles =>
      (super.noSuchMethod(
            Invocation.getter(#allProfiles),
            returnValue: <String, _i7.UserProfile>{},
          )
          as Map<String, _i7.UserProfile>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void setPersistentCache(_i8.ProfileCacheService? cacheService) =>
      super.noSuchMethod(
        Invocation.method(#setPersistentCache, [cacheService]),
        returnValueForMissingStub: null,
      );

  @override
  _i7.UserProfile? getCachedProfile(String? pubkey) =>
      (super.noSuchMethod(Invocation.method(#getCachedProfile, [pubkey]))
          as _i7.UserProfile?);

  @override
  bool hasProfile(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#hasProfile, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  bool shouldSkipProfileFetch(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#shouldSkipProfileFetch, [pubkey]),
            returnValue: false,
          )
          as bool);

  @override
  void markProfileAsMissing(String? pubkey) => super.noSuchMethod(
    Invocation.method(#markProfileAsMissing, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> updateCachedProfile(_i7.UserProfile? profile) =>
      (super.noSuchMethod(
            Invocation.method(#updateCachedProfile, [profile]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<_i7.UserProfile?> fetchProfile(
    String? pubkey, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i3.Future<_i7.UserProfile?>.value(),
          )
          as _i3.Future<_i7.UserProfile?>);

  @override
  _i3.Future<void> prefetchProfilesImmediately(List<String>? pubkeys) =>
      (super.noSuchMethod(
            Invocation.method(#prefetchProfilesImmediately, [pubkeys]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> fetchMultipleProfiles(
    List<String>? pubkeys, {
    bool? forceRefresh = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchMultipleProfiles,
              [pubkeys],
              {#forceRefresh: forceRefresh},
            ),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String getDisplayName(String? pubkey) =>
      (super.noSuchMethod(
            Invocation.method(#getDisplayName, [pubkey]),
            returnValue: _i9.dummyValue<String>(
              this,
              Invocation.method(#getDisplayName, [pubkey]),
            ),
          )
          as String);

  @override
  void removeProfile(String? pubkey) => super.noSuchMethod(
    Invocation.method(#removeProfile, [pubkey]),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<List<_i7.UserProfile>> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i3.Future<List<_i7.UserProfile>>.value(
              <_i7.UserProfile>[],
            ),
          )
          as _i3.Future<List<_i7.UserProfile>>);

  @override
  _i3.Stream<_i7.UserProfile> searchUsersStream(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsersStream, [query], {#limit: limit}),
            returnValue: _i3.Stream<_i7.UserProfile>.empty(),
          )
          as _i3.Stream<_i7.UserProfile>);

  @override
  void handleProfileEventForTesting(_i10.Event? event) => super.noSuchMethod(
    Invocation.method(#handleProfileEventForTesting, [event]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i11.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
