// Mocks generated by Mockito 5.4.6 from annotations
// in openvine/test/unit/services/nip17_inbox_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:nostr_client/src/models/models.dart' as _i3;
import 'package:nostr_client/src/nostr_client.dart' as _i7;
import 'package:nostr_key_manager/src/nostr_key_manager.dart' as _i2;
import 'package:nostr_sdk/nostr_sdk.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKeychain_0 extends _i1.SmartFake implements _i2.Keychain {
  _FakeKeychain_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResult_1 extends _i1.SmartFake implements _i3.CountResult {
  _FakeCountResult_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeNostrSigner_2 extends _i1.SmartFake implements _i4.NostrSigner {
  _FakeNostrSigner_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelay_3 extends _i1.SmartFake implements _i4.Relay {
  _FakeRelay_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRelayPool_4 extends _i1.SmartFake implements _i4.RelayPool {
  _FakeRelayPool_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCountResponse_5 extends _i1.SmartFake implements _i4.CountResponse {
  _FakeCountResponse_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NostrKeyManager].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrKeyManager extends _i1.Mock implements _i2.NostrKeyManager {
  MockNostrKeyManager() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  bool get hasBackup =>
      (super.noSuchMethod(Invocation.getter(#hasBackup), returnValue: false)
          as bool);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i2.Keychain> generateKeys() =>
      (super.noSuchMethod(
            Invocation.method(#generateKeys, []),
            returnValue: _i5.Future<_i2.Keychain>.value(
              _FakeKeychain_0(this, Invocation.method(#generateKeys, [])),
            ),
          )
          as _i5.Future<_i2.Keychain>);

  @override
  _i5.Future<_i2.Keychain> importPrivateKey(String? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#importPrivateKey, [privateKey]),
            returnValue: _i5.Future<_i2.Keychain>.value(
              _FakeKeychain_0(
                this,
                Invocation.method(#importPrivateKey, [privateKey]),
              ),
            ),
          )
          as _i5.Future<_i2.Keychain>);

  @override
  _i5.Future<_i2.Keychain> importFromNsec(String? nsec) =>
      (super.noSuchMethod(
            Invocation.method(#importFromNsec, [nsec]),
            returnValue: _i5.Future<_i2.Keychain>.value(
              _FakeKeychain_0(this, Invocation.method(#importFromNsec, [nsec])),
            ),
          )
          as _i5.Future<_i2.Keychain>);

  @override
  String exportPrivateKey() =>
      (super.noSuchMethod(
            Invocation.method(#exportPrivateKey, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#exportPrivateKey, []),
            ),
          )
          as String);

  @override
  String exportAsNsec() =>
      (super.noSuchMethod(
            Invocation.method(#exportAsNsec, []),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#exportAsNsec, []),
            ),
          )
          as String);

  @override
  _i5.Future<Map<String, dynamic>> replaceKeyWithBackup() =>
      (super.noSuchMethod(
            Invocation.method(#replaceKeyWithBackup, []),
            returnValue: _i5.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i5.Future<Map<String, dynamic>>);

  @override
  _i5.Future<void> restoreFromBackup() =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromBackup, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> clearBackup() =>
      (super.noSuchMethod(
            Invocation.method(#clearBackup, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<String>> createMnemonicBackup() =>
      (super.noSuchMethod(
            Invocation.method(#createMnemonicBackup, []),
            returnValue: _i5.Future<List<String>>.value(<String>[]),
          )
          as _i5.Future<List<String>>);

  @override
  _i5.Future<_i2.Keychain> restoreFromMnemonic(List<String>? mnemonic) =>
      (super.noSuchMethod(
            Invocation.method(#restoreFromMnemonic, [mnemonic]),
            returnValue: _i5.Future<_i2.Keychain>.value(
              _FakeKeychain_0(
                this,
                Invocation.method(#restoreFromMnemonic, [mnemonic]),
              ),
            ),
          )
          as _i5.Future<_i2.Keychain>);

  @override
  _i5.Future<bool> verifyBackup(List<String>? mnemonic, String? privateKey) =>
      (super.noSuchMethod(
            Invocation.method(#verifyBackup, [mnemonic, privateKey]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<void> clearKeys() =>
      (super.noSuchMethod(
            Invocation.method(#clearKeys, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, dynamic> getIdentitySummary() =>
      (super.noSuchMethod(
            Invocation.method(#getIdentitySummary, []),
            returnValue: <String, dynamic>{},
          )
          as Map<String, dynamic>);
}

/// A class which mocks [NostrClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostrClient extends _i1.Mock implements _i7.NostrClient {
  MockNostrClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  bool get isInitialized =>
      (super.noSuchMethod(Invocation.getter(#isInitialized), returnValue: false)
          as bool);

  @override
  bool get isDisposed =>
      (super.noSuchMethod(Invocation.getter(#isDisposed), returnValue: false)
          as bool);

  @override
  bool get hasKeys =>
      (super.noSuchMethod(Invocation.getter(#hasKeys), returnValue: false)
          as bool);

  @override
  List<String> get configuredRelays =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  List<String> get connectedRelays =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelays),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  int get connectedRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#connectedRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  int get configuredRelayCount =>
      (super.noSuchMethod(
            Invocation.getter(#configuredRelayCount),
            returnValue: 0,
          )
          as int);

  @override
  Map<String, _i3.RelayConnectionStatus> get relayStatuses =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatuses),
            returnValue: <String, _i3.RelayConnectionStatus>{},
          )
          as Map<String, _i3.RelayConnectionStatus>);

  @override
  _i5.Stream<Map<String, _i3.RelayConnectionStatus>> get relayStatusStream =>
      (super.noSuchMethod(
            Invocation.getter(#relayStatusStream),
            returnValue:
                _i5.Stream<Map<String, _i3.RelayConnectionStatus>>.empty(),
          )
          as _i5.Stream<Map<String, _i3.RelayConnectionStatus>>);

  @override
  String get primaryRelay =>
      (super.noSuchMethod(
            Invocation.getter(#primaryRelay),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#primaryRelay),
            ),
          )
          as String);

  @override
  _i5.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.Event?> publishEvent(
    _i4.Event? event, {
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #publishEvent,
              [event],
              {#targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<List<_i4.Event>> queryEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i5.Future<List<_i4.Event>>);

  @override
  _i5.Future<_i3.CountResult> countEvents(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i3.CountResult>.value(
              _FakeCountResult_1(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #subscriptionId: subscriptionId,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.CountResult>);

  @override
  _i5.Future<_i4.Event?> fetchEventById(
    String? eventId, {
    String? relayUrl,
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchEventById,
              [eventId],
              {
                #relayUrl: relayUrl,
                #useGateway: useGateway,
                #useCache: useCache,
              },
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> fetchProfile(
    String? pubkey, {
    bool? useGateway = true,
    bool? useCache = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #fetchProfile,
              [pubkey],
              {#useGateway: useGateway, #useCache: useCache},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Stream<_i4.Event> subscribe(
    List<_i4.Filter>? filters, {
    String? subscriptionId,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters],
              {
                #subscriptionId: subscriptionId,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i5.Stream<_i4.Event>.empty(),
          )
          as _i5.Stream<_i4.Event>);

  @override
  _i5.Future<void> unsubscribe(String? subscriptionId) =>
      (super.noSuchMethod(
            Invocation.method(#unsubscribe, [subscriptionId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> closeAllSubscriptions() =>
      (super.noSuchMethod(
            Invocation.method(#closeAllSubscriptions, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> addRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#addRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> removeRelay(String? relayUrl) =>
      (super.noSuchMethod(
            Invocation.method(#removeRelay, [relayUrl]),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<Map<String, dynamic>?> getRelayStats() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStats, []),
            returnValue: _i5.Future<Map<String, dynamic>?>.value(),
          )
          as _i5.Future<Map<String, dynamic>?>);

  @override
  _i5.Future<void> retryDisconnectedRelays() =>
      (super.noSuchMethod(
            Invocation.method(#retryDisconnectedRelays, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> forceReconnectAll() =>
      (super.noSuchMethod(
            Invocation.method(#forceReconnectAll, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  Map<String, bool> getRelayStatus() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayStatus, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);

  @override
  _i5.Future<_i4.Event?> sendLike(
    String? eventId, {
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [eventId],
              {
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> sendRepost(
    String? eventId, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [eventId],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> sendContactList(
    _i4.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Stream<_i4.Event> searchVideos(
    String? query, {
    List<String>? authors,
    DateTime? since,
    DateTime? until,
    int? limit,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #searchVideos,
              [query],
              {#authors: authors, #since: since, #until: until, #limit: limit},
            ),
            returnValue: _i5.Stream<_i4.Event>.empty(),
          )
          as _i5.Stream<_i4.Event>);

  @override
  _i5.Stream<_i4.Event> searchUsers(String? query, {int? limit}) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [query], {#limit: limit}),
            returnValue: _i5.Stream<_i4.Event>.empty(),
          )
          as _i5.Stream<_i4.Event>);

  @override
  _i5.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);
}

/// A class which mocks [Nostr].
///
/// See the documentation for Mockito's code generation for more information.
class MockNostr extends _i1.Mock implements _i4.Nostr {
  MockNostr() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.NostrSigner get nostrSigner =>
      (super.noSuchMethod(
            Invocation.getter(#nostrSigner),
            returnValue: _FakeNostrSigner_2(
              this,
              Invocation.getter(#nostrSigner),
            ),
          )
          as _i4.NostrSigner);

  @override
  _i4.Relay Function(String) get tempRelayGener =>
      (super.noSuchMethod(
            Invocation.getter(#tempRelayGener),
            returnValue: (String __p0) =>
                _FakeRelay_3(this, Invocation.getter(#tempRelayGener)),
          )
          as _i4.Relay Function(String));

  @override
  String get publicKey =>
      (super.noSuchMethod(
            Invocation.getter(#publicKey),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.getter(#publicKey),
            ),
          )
          as String);

  @override
  _i4.RelayPool get relayPool =>
      (super.noSuchMethod(
            Invocation.getter(#relayPool),
            returnValue: _FakeRelayPool_4(this, Invocation.getter(#relayPool)),
          )
          as _i4.RelayPool);

  @override
  set nostrSigner(_i4.NostrSigner? value) => super.noSuchMethod(
    Invocation.setter(#nostrSigner, value),
    returnValueForMissingStub: null,
  );

  @override
  set onNotice(dynamic Function(String, String)? value) => super.noSuchMethod(
    Invocation.setter(#onNotice, value),
    returnValueForMissingStub: null,
  );

  @override
  set tempRelayGener(_i4.Relay Function(String)? value) => super.noSuchMethod(
    Invocation.setter(#tempRelayGener, value),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<_i4.Event?> sendLike(
    String? id, {
    String? pubkey,
    String? content,
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendLike,
              [id],
              {
                #pubkey: pubkey,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> deleteEvent(
    String? eventId, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvent,
              [eventId],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> deleteEvents(
    List<String>? eventIds, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteEvents,
              [eventIds],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> sendRepost(
    String? id, {
    String? relayAddr,
    String? content = '',
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendRepost,
              [id],
              {
                #relayAddr: relayAddr,
                #content: content,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
              },
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> sendContactList(
    _i4.ContactList? contacts,
    String? content, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendContactList,
              [contacts, content],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  _i5.Future<_i4.Event?> sendEvent(
    _i4.Event? event, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #sendEvent,
              [event],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  void checkEventSign(_i4.Event? event) => super.noSuchMethod(
    Invocation.method(#checkEventSign, [event]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> signEvent(_i4.Event? event) =>
      (super.noSuchMethod(
            Invocation.method(#signEvent, [event]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<_i4.Event?> broadcase(
    _i4.Event? event, {
    List<String>? tempRelays,
    List<String>? targetRelays,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #broadcase,
              [event],
              {#tempRelays: tempRelays, #targetRelays: targetRelays},
            ),
            returnValue: _i5.Future<_i4.Event?>.value(),
          )
          as _i5.Future<_i4.Event?>);

  @override
  void close() => super.noSuchMethod(
    Invocation.method(#close, []),
    returnValueForMissingStub: null,
  );

  @override
  void addInitQuery(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i4.Event)? onEvent, {
    String? id,
    Function? onComplete,
  }) => super.noSuchMethod(
    Invocation.method(
      #addInitQuery,
      [filters, onEvent],
      {#id: id, #onComplete: onComplete},
    ),
    returnValueForMissingStub: null,
  );

  @override
  bool tempRelayHasSubscription(String? relayAddr) =>
      (super.noSuchMethod(
            Invocation.method(#tempRelayHasSubscription, [relayAddr]),
            returnValue: false,
          )
          as bool);

  @override
  String subscribe(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i4.Event)? onEvent, {
    String? id,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
    void Function()? onEose,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #subscribe,
              [filters, onEvent],
              {
                #id: id,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
                #onEose: onEose,
              },
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #subscribe,
                [filters, onEvent],
                {
                  #id: id,
                  #tempRelays: tempRelays,
                  #targetRelays: targetRelays,
                  #relayTypes: relayTypes,
                  #sendAfterAuth: sendAfterAuth,
                  #onEose: onEose,
                },
              ),
            ),
          )
          as String);

  @override
  void unsubscribe(String? id) => super.noSuchMethod(
    Invocation.method(#unsubscribe, [id]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<List<_i4.Event>> queryEvents(
    List<Map<String, dynamic>>? filters, {
    String? id,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryEvents,
              [filters],
              {
                #id: id,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
              },
            ),
            returnValue: _i5.Future<List<_i4.Event>>.value(<_i4.Event>[]),
          )
          as _i5.Future<List<_i4.Event>>);

  @override
  _i5.Future<_i4.CountResponse> countEvents(
    List<Map<String, dynamic>>? filters, {
    String? id,
    List<String>? tempRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    Duration? timeout = const Duration(seconds: 10),
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #countEvents,
              [filters],
              {
                #id: id,
                #tempRelays: tempRelays,
                #relayTypes: relayTypes,
                #timeout: timeout,
              },
            ),
            returnValue: _i5.Future<_i4.CountResponse>.value(
              _FakeCountResponse_5(
                this,
                Invocation.method(
                  #countEvents,
                  [filters],
                  {
                    #id: id,
                    #tempRelays: tempRelays,
                    #relayTypes: relayTypes,
                    #timeout: timeout,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i4.CountResponse>);

  @override
  _i5.Future<String> query(
    List<Map<String, dynamic>>? filters,
    dynamic Function(_i4.Event)? onEvent, {
    String? id,
    Function? onComplete,
    List<String>? tempRelays,
    List<String>? targetRelays,
    List<int>? relayTypes = const [1, 2, 3, 4],
    bool? sendAfterAuth = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #query,
              [filters, onEvent],
              {
                #id: id,
                #onComplete: onComplete,
                #tempRelays: tempRelays,
                #targetRelays: targetRelays,
                #relayTypes: relayTypes,
                #sendAfterAuth: sendAfterAuth,
              },
            ),
            returnValue: _i5.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(
                  #query,
                  [filters, onEvent],
                  {
                    #id: id,
                    #onComplete: onComplete,
                    #tempRelays: tempRelays,
                    #targetRelays: targetRelays,
                    #relayTypes: relayTypes,
                    #sendAfterAuth: sendAfterAuth,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  String queryByFilters(
    Map<String, List<Map<String, dynamic>>>? filtersMap,
    dynamic Function(_i4.Event)? onEvent, {
    String? id,
    Function? onComplete,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #queryByFilters,
              [filtersMap, onEvent],
              {#id: id, #onComplete: onComplete},
            ),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(
                #queryByFilters,
                [filtersMap, onEvent],
                {#id: id, #onComplete: onComplete},
              ),
            ),
          )
          as String);

  @override
  _i5.Future<bool> addRelay(
    _i4.Relay? relay, {
    bool? autoSubscribe = false,
    bool? init = false,
    int? relayType = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #addRelay,
              [relay],
              {
                #autoSubscribe: autoSubscribe,
                #init: init,
                #relayType: relayType,
              },
            ),
            returnValue: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  void removeRelay(String? url, {int? relayType = 1}) => super.noSuchMethod(
    Invocation.method(#removeRelay, [url], {#relayType: relayType}),
    returnValueForMissingStub: null,
  );

  @override
  List<_i4.Relay> activeRelays() =>
      (super.noSuchMethod(
            Invocation.method(#activeRelays, []),
            returnValue: <_i4.Relay>[],
          )
          as List<_i4.Relay>);

  @override
  _i4.Relay? getRelay(String? url) =>
      (super.noSuchMethod(Invocation.method(#getRelay, [url])) as _i4.Relay?);

  @override
  _i4.Relay? getTempRelay(String? url) =>
      (super.noSuchMethod(Invocation.method(#getTempRelay, [url]))
          as _i4.Relay?);

  @override
  void reconnect() => super.noSuchMethod(
    Invocation.method(#reconnect, []),
    returnValueForMissingStub: null,
  );

  @override
  List<String> getExtralReadableRelays(
    List<String>? extralRelays,
    int? maxRelayNum,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getExtralReadableRelays, [
              extralRelays,
              maxRelayNum,
            ]),
            returnValue: <String>[],
          )
          as List<String>);

  @override
  void removeTempRelay(String? addr) => super.noSuchMethod(
    Invocation.method(#removeTempRelay, [addr]),
    returnValueForMissingStub: null,
  );

  @override
  bool readable() =>
      (super.noSuchMethod(Invocation.method(#readable, []), returnValue: false)
          as bool);

  @override
  bool writable() =>
      (super.noSuchMethod(Invocation.method(#writable, []), returnValue: false)
          as bool);

  @override
  bool isReadOnly() =>
      (super.noSuchMethod(
            Invocation.method(#isReadOnly, []),
            returnValue: false,
          )
          as bool);

  @override
  void setRelayAlwaysAuth(String? relayUrl, bool? alwaysAuth) =>
      super.noSuchMethod(
        Invocation.method(#setRelayAlwaysAuth, [relayUrl, alwaysAuth]),
        returnValueForMissingStub: null,
      );

  @override
  void configureRelayAuth(Map<String, bool>? relayAuthConfig) =>
      super.noSuchMethod(
        Invocation.method(#configureRelayAuth, [relayAuthConfig]),
        returnValueForMissingStub: null,
      );

  @override
  Map<String, bool> getRelayAuthConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getRelayAuthConfig, []),
            returnValue: <String, bool>{},
          )
          as Map<String, bool>);
}
